### ISSUE TITLE
Authentication protected links don't work if starting with empty database

### ISSUE THREAD

**Issue by Xarkam** [SOFTINUX/Base#21]
If the application start with an empty database, we need to restart te application for access to authentication protected links to work, such as "extension1/admin" after seeding database with permissions, groups, etc...

We need to find a solution to update what's missing without having to restart the application.

**Comment by postb99** [comment]
Analysis: at application startup, the AddAuthorizationPolicies class calls AddAuthorization() on services collection. It also updates a set of known policy names. These items are not updated after creation of permissions in database. They should be updated by adding relevant code to call in seeding database code.

**Comment by postb99** [comment]
Work in progress: the injected services collection is empty in seed database controller. Try changing in Startup.cs:
replace:
services_.AddSingleton<IServiceCollection, ServiceCollection>();
by:
services_.AddSingleton<IServiceCollection, _services>();

**Comment by postb99** [comment]
I've found a totally different approach: instead of using AuthorizeAttribute and policies, the 4th answer of [this SO post](https://stackoverflow.com/questions/31464359/how-do-you-create-a-custom-authorizeattribute-in-asp-net-core/40824351#40824351) uses ClaimRequirementAttribute. This is way more easy to understand and use, because claims can be determined and set on current user at any time while the application runs.
